### ISSUE TITLE
"Unbang"

### ISSUE THREAD

**Issue by expede** [expede/exceptional#3]
I'm not 100% sold on this idea yet, but have come across a few times that it would have been useful. Essentially wrap a `!`ed function in a `rescue`, and return the exception struct, and return it as a value.

Ex.

```elixir
unbang do: File.read!("no_file.txt")
#=> %File.Error{
#     reason: "could not read file \"no_file.txt\": no such file or directory"
#     action: "",
#     path: nil
#   }

# ROUGH outline of in flow
path
|> unbang(File.read!).()
~> upload_file
```

Note that the above syntax would likely be changed. Just a sketch of the idea.

**Comment by OvermindDL1** [comment]
I absolutely would love something that catches an exception from a call and returns the exception struct and/or error tuple (for erlang-style exceptions perhaps, maybe wrap them in an actual exception then?).
